### ISSUE TITLE
关于qc反代三方应用访问端设置问题

### ISSUE THREAD

**Issue by carlliuxx** [lyc8503/lyc8503#1]
您好，按照您文章的设置，我进行到：
“此时如果在外网环境 (如手机流量) 直接打开浏览器访问 你的 QC 的 ID.quickconnect.to/reverse_proxy, 浏览器能显示 Bad Request 则代表服务器配置正确.”
这一步都都是OK的，后面就不会了，怎么设置都无法成功，本人代码小白，请问这么设置对么？mac版的v2rayx：

<img width="916" alt="截屏2022-03-04 14 59 29" src="https://user-images.githubusercontent.com/52060495/156715748-11a4d8cf-2331-4320-a716-0a27e5e053b3.png">
<img width="551" alt="截屏2022-03-04 14 59 38" src="https://user-images.githubusercontent.com/52060495/156715759-92b5b048-a607-4f6b-8ca9-a780ccf2ec9a.png">
<img width="519" alt="截屏2022-03-04 14 59 43" src="https://user-images.githubusercontent.com/52060495/156715764-ba2e57a4-15f7-4087-a60f-f7a7a59d1d64.png">
<img width="865" alt="截屏2022-03-04 14 59 55" src="https://user-images.githubusercontent.com/52060495/156715767-3348f1da-d52b-4197-9efb-c66a1ba745dd.png">

**Comment by lyc8503** [comment]
是 `Cookie: type=tunnel`? 是冒号而不是 pipe?

**Comment by carlliuxx** [comment]
`{
    "outbounds": [
        {
            "_QV2RAY_USE_GLOBAL_FORWARD_PROXY_": false,
            "mux": {
                "concurrency": 1,
                "enabled": false
            },
            "protocol": "vmess",
            "sendThrough": "0.0.0.0",
            "settings": {
                "vnext": [
                    {
                        "address": "xxxxx.cn1.quickconnect.cn",
                        "port": 443,
                        "users": [
                            {
                                "id": "xxxxx"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "wsSettings": {
                    "headers": {
                        "Cookie": "type=tunnel"
                    },
                    "path": "/reverse_proxy"
                }
            },
            "tag": "qc"
        }
    ]
}
`

这是目前的配置信息，在ui界面里写成pipe才能在配置文件变成冒号。

您看看是不是配置文件哪里错了？


另外，请问设置好以后在哪里访问？我是用浏览器访问我的xxxxx.cn1.quickconnect.cn:8096，理论上是可以访问通的么？？？

谢谢

**Comment by lyc8503** [comment]
配置文件好像没有问题, 但你访问的方法错了.
设置好之后你需要通过 Socks 代理访问目标应用.

你可以尝试将 v2ray 设为全局代理模式, 选中 qc 代理进行测试, 这时候直接使用你内网的 IP 地址进行访问.
如果要访问方便的话, 可以自己设置分流规则, 将内网网段 IP 的代理设置为 qc 即可.

**Comment by carlliuxx** [comment]
`设置好之后你需要通过 Socks 代理访问目标应用.`

其实我的目的是希望用qc代理访问我在别的设备上搭建的emby媒体服务器，这个emby的端口是8096，在内网环境下可以通过浏览器输入“设备ip:8096”访问，现在：
1、我做了这个设备的8096的端口映射
2、在v2ray中设置如刚才的截图

然后我应该怎么访问媒体服务器呢？您说的用socks访问如何操作？我没明白～

**Comment by carlliuxx** [comment]
直接访问群晖，似乎已经反代了～那为啥emby的就不行呢？😂

**Comment by lyc8503** [comment]
你可能混淆了相关概念, `做了设备 8096 的端口映射`是在路由器上完成的吗? 如果你有公网 IP, 则不需要使用 QC 反向代理, 如果使用反向代理则不需要设置端口映射.

假设现在你在外网, 直接将 v2ray 设置为全局模式, , 理论上就能使用 `设备ip:8096` 访问 emby 了.
如果不能, 可能是 v2rayx 默认绕过了局域网地址, 你可能需要手动更改相关的路由配置.

除了配置 v2ray, 现在你还有两种选择:
1. 如果你有公网 IP (需要自己向运营商申请), 可以选择设置 DDNS 和路由器端口转发, 不需要 qc 反代.
2. 你可以参考我博客提到的 `初级版本 (HTTP) 和灵感来源` 部分引用的文章设置 emby 反代, 则不需要 v2ray, 可以直接使用 quickconnect.to 的域名访问.

**Comment by lyc8503** [comment]
v2rayN 的默认路由设置如图, geoip:private 会走 direct (不使用代理), 需要将这条规则删掉, v2rayX 的设置我不太清楚但应该类似.
![image](https://user-images.githubusercontent.com/36782264/156727072-c66a5f4a-c926-480c-96c3-0c7128a96d99.png)

**Comment by lyc8503** [comment]
如果你只是想用 emby 的话, 这篇文章 (https://null.studio/2020/02/16/access-thirdparty-web-via-synology-quickconnect/) 中的配置方法更加简单直接. 只有需要使用非 HTTP 应用时才需要配置 v2ray.

**Comment by carlliuxx** [comment]
他似乎只能代理127.0.0.1的，不能代理局域网中的其他设备吧？

**Comment by lyc8503** [comment]
是可以代理局域网中其他设备的, 只需要将 127.0.0.1 替换成对应设备的 IP.

**Comment by carlliuxx** [comment]
哦是么？那就是我设置不对，我试过没成功，那我再试试～另外我想把群晖里虚拟机的windows通过微软的远程桌面app来访问，是不是就只能用你这个才能实现了？

**Comment by lyc8503** [comment]
是的 远程桌面必须要使用 v2ray 了, 而且 Windows 的远程桌面不走 v2ray 的代理, 可能需要第三方客户端或者 TUN 模式的代理才行.

**Comment by carlliuxx** [comment]
设置了全局还是不行，但是直接访问群晖自己的页面，从地址看已经转成局域网地址开头了:

`https://192-186-31-126.xxxxxx.direct.quickconnect.to:5001/#/signin`

这是不是说明代理已经通了，这是访问别的端口不行？？

**Comment by lyc8503** [comment]
我自己测试的时候即使在内网群晖也不会跳到这样的地址, 只会直接跳到 https://x.x.x.x:5001.

那你挂上代理尝试一下访问 https://192.186.31.126:5001/ 试试?

**Comment by carlliuxx** [comment]
已解决，我自己糊涂了，应该用内网IP：8096访问，我一直用的是qc的网址：8096访问的～谢谢您的耐心解答～回头有空再尝试一下tun～感谢～～～
