### ISSUE TITLE
关于QC反代docker容器的问题

### ISSUE THREAD

**Issue by DarkMastray** [lyc8503/lyc8503#10]
本人nginx配置小白，
这几天看了好几个博客都写到可以通过配置nginx来实现通过QC代理第三方的应用，就想自己也试一下。
但是不知道是否是由于我的应用都装在docker内的缘故，即便按照教程配置了dsm.*.conf文件，也无法代理成功。
（例：[通过群晖的 QuickConnect 访问第三方应用](https://null.studio/2020/02/16/access-thirdparty-web-via-synology-quickconnect/)）
所以想请问下这种问题是否可以解决呢？

**Comment by lyc8503** [comment]
装在 docker 里是不影响 Nginx 反代的, 我也是使用的 docker, 我现在群晖 6.2 这种方法仍然有效, 你的群晖版本是否是 6.2? Nginx 无法访问具体是什么症状, 尝试搜索下对应的报错?
